import { Container } from 'inversify';
import { TYPES } from 'src/shared/constants/types';

import { IGetAllUsersUseCase } from 'src/domain/interfaces/use-cases/admin/user/IGetAllUsersUseCase';
import { IBlockUserUseCase } from 'src/domain/interfaces/use-cases/admin/user/IBlockUserUseCase';
import { IAdminGetUserByIdUseCase } from 'src/domain/interfaces/use-cases/admin/user/IAdminGetUserByIdUseCase';
import { IGetAllCompaniesUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetAllCompaniesUseCase';
import { IGetCompaniesWithVerificationUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetCompaniesWithVerificationUseCase';
import { IVerifyCompanyUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IVerifyCompanyUseCase';
import { IGetPendingCompaniesUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetPendingCompaniesUseCase';
import { IGetCompanyByIdUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetCompanyByIdUseCase';
import { IAdminGetAllJobsUseCase } from 'src/domain/interfaces/use-cases/admin/job/IAdminGetAllJobsUseCase';
import { IAdminGetJobByIdUseCase } from 'src/domain/interfaces/use-cases/admin/job/IAdminGetJobByIdUseCase';
import { IAdminUpdateJobStatusUseCase } from 'src/domain/interfaces/use-cases/admin/job/IAdminUpdateJobStatusUseCase';
import { IAdminDeleteJobUseCase } from 'src/domain/interfaces/use-cases/admin/job/IAdminDeleteJobUseCase';
import { IAdminGetJobStatsUseCase } from 'src/domain/interfaces/use-cases/admin/analytics/IAdminGetJobStatsUseCase';
import { ICreateJobCategoryUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-categorys/ICreateJobCategoryUseCase';
import { IGetAllJobCategoriesUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-categorys/IGetAllJobCategoriesUseCase';
import { IGetJobCategoryByIdUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-categorys/IGetJobCategoryByIdUseCase';
import { IUpdateJobCategoryUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-categorys/IUpdateJobCategoryUseCase';
import { IDeleteJobCategoryUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-categorys/IDeleteJobCategoryUseCase';
import { ICreateSkillUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/skills/ICreateSkillUseCase';
import { IGetAllSkillsUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/skills/IGetAllSkillsUseCase';
import { IGetSkillByIdUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/skills/IGetSkillByIdUseCase';
import { IUpdateSkillUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/skills/IUpdateSkillUseCase';
import { IDeleteSkillUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/skills/IDeleteSkillUseCase';
import { ICreateJobRoleUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-roles/ICreateJobRoleUseCase';
import { IGetAllJobRolesUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-roles/IGetAllJobRolesUseCase';
import { IGetJobRoleByIdUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-roles/IGetJobRoleByIdUseCase';
import { IUpdateJobRoleUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-roles/IUpdateJobRoleUseCase';
import { IDeleteJobRoleUseCase } from 'src/domain/interfaces/use-cases/admin/attributes/job-roles/IDeleteJobRoleUseCase';
import { ICreateSubscriptionPlanUseCase } from 'src/domain/interfaces/use-cases/admin/subscription/ICreateSubscriptionPlanUseCase';
import { IGetAllSubscriptionPlansUseCase } from 'src/domain/interfaces/use-cases/admin/subscription/IGetAllSubscriptionPlansUseCase';
import { IGetSubscriptionPlanByIdUseCase } from 'src/domain/interfaces/use-cases/admin/subscription/IGetSubscriptionPlanByIdUseCase';
import { IUpdateSubscriptionPlanUseCase } from 'src/domain/interfaces/use-cases/admin/subscription/IUpdateSubscriptionPlanUseCase';
import { IGetAllPaymentOrdersUseCase } from 'src/domain/interfaces/use-cases/admin/payments/IGetAllPaymentOrdersUseCase';
import { IGetAdminDashboardStatsUseCase } from 'src/domain/interfaces/use-cases/admin/analytics/IGetAdminDashboardStatsUseCase';

import { GetAllUsersUseCase } from 'src/application/use-cases/admin/user/get-all-users.use-case';
import { BlockUserUseCase } from 'src/application/use-cases/admin/user/block-user.use-case';
import { GetUserByIdUseCase as AdminGetUserByIdUseCase } from 'src/application/use-cases/admin/user/get-user-by-id.use-case';
import { GetAllCompaniesUseCase } from 'src/application/use-cases/admin/companies/get-all-companies.use-case';
import { GetCompaniesWithVerificationUseCase } from 'src/application/use-cases/admin/companies/get-companies-with-verification.use-case';
import { VerifyCompanyUseCase } from 'src/application/use-cases/admin/companies/verify-company.use-case';
import { GetPendingCompaniesUseCase } from 'src/application/use-cases/admin/companies/get-pending-companies.use-case';
import { GetCompanyByIdUseCase } from 'src/application/use-cases/admin/companies/get-company-by-id.use-case';
import { GetAllJobsUseCase } from 'src/application/use-cases/admin/job/get-all-jobs.use-case';
import { AdminGetJobByIdUseCase } from 'src/application/use-cases/admin/job/get-job-by-id.use-case';
import { AdminUpdateJobStatusUseCase } from 'src/application/use-cases/admin/job/update-job-status.use-case';
import { AdminDeleteJobUseCase } from 'src/application/use-cases/admin/job/delete-job.use-case';
import { AdminGetJobStatsUseCase } from 'src/application/use-cases/admin/analytics/get-job-stats.use-case';
import { CreateJobCategoryUseCase } from 'src/application/use-cases/admin/attributes/job-categorys/create-job-category.use-case';
import { GetAllJobCategoriesUseCase } from 'src/application/use-cases/admin/attributes/job-categorys/get-all-job-categories.use-case';
import { GetJobCategoryByIdUseCase } from 'src/application/use-cases/admin/attributes/job-categorys/get-job-category-by-id.use-case';
import { UpdateJobCategoryUseCase } from 'src/application/use-cases/admin/attributes/job-categorys/update-job-category.use-case';
import { DeleteJobCategoryUseCase } from 'src/application/use-cases/admin/attributes/job-categorys/delete-job-category.use-case';
import { CreateSkillUseCase } from 'src/application/use-cases/admin/attributes/skills/create-skill.use-case';
import { GetAllSkillsUseCase } from 'src/application/use-cases/admin/attributes/skills/get-all-skills.use-case';
import { GetSkillByIdUseCase } from 'src/application/use-cases/admin/attributes/skills/get-skill-by-id.use-case';
import { UpdateSkillUseCase } from 'src/application/use-cases/admin/attributes/skills/update-skill.use-case';
import { DeleteSkillUseCase } from 'src/application/use-cases/admin/attributes/skills/delete-skill.use-case';
import { CreateJobRoleUseCase } from 'src/application/use-cases/admin/attributes/job-roles/create-job-role.use-case';
import { GetAllJobRolesUseCase } from 'src/application/use-cases/admin/attributes/job-roles/get-all-job-roles.use-case';
import { GetJobRoleByIdUseCase } from 'src/application/use-cases/admin/attributes/job-roles/get-job-role-by-id.use-case';
import { UpdateJobRoleUseCase } from 'src/application/use-cases/admin/attributes/job-roles/update-job-role.use-case';
import { DeleteJobRoleUseCase } from 'src/application/use-cases/admin/attributes/job-roles/delete-job-role.use-case';
import { CreateSubscriptionPlanUseCase } from 'src/application/use-cases/admin/subscription/create-subscription-plan.use-case';
import { GetAllSubscriptionPlansUseCase } from 'src/application/use-cases/admin/subscription/get-all-subscription-plans.use-case';
import { GetSubscriptionPlanByIdUseCase } from 'src/application/use-cases/admin/subscription/get-subscription-plan-by-id.use-case';
import { UpdateSubscriptionPlanUseCase } from 'src/application/use-cases/admin/subscription/update-subscription-plan.use-case';
import { GetAllPaymentOrdersUseCase } from 'src/application/use-cases/admin/payments/get-all-payment-orders.use-case';
import { GetAdminDashboardStatsUseCase } from 'src/application/use-cases/admin/dashboard/get-admin-dashboard-stats.use-case';

import { AdminUserController } from 'src/presentation/controllers/admin/admin-user.controller';
import { AdminCompanyController } from 'src/presentation/controllers/admin/admin-company.controller';
import { AdminJobController } from 'src/presentation/controllers/admin/admin-job.controller';
import { AdminJobCategoryController } from 'src/presentation/controllers/admin/admin-job-category.controller';
import { AdminSkillController } from 'src/presentation/controllers/admin/admin-skill.controller';
import { AdminJobRoleController } from 'src/presentation/controllers/admin/admin-job-role.controller';
import { AdminSubscriptionPlanController } from 'src/presentation/controllers/admin/admin-subscription-plan.controller';
import { AdminPaymentOrderController } from 'src/presentation/controllers/admin/admin-payment-order.controller';
import { AdminDashboardController } from 'src/presentation/controllers/admin/admin-dashboard.controller';

export function registerAdminDi(container: Container): void {
  container.bind<IGetAllUsersUseCase>(TYPES.GetAllUsersUseCase).to(GetAllUsersUseCase);
  container.bind<IBlockUserUseCase>(TYPES.BlockUserUseCase).to(BlockUserUseCase);
  container.bind<IAdminGetUserByIdUseCase>(TYPES.AdminGetUserByIdUseCase).to(AdminGetUserByIdUseCase);
  container.bind<IGetAllCompaniesUseCase>(TYPES.GetAllCompaniesUseCase).to(GetAllCompaniesUseCase);
  container.bind<IGetCompaniesWithVerificationUseCase>(TYPES.GetCompaniesWithVerificationUseCase).to(GetCompaniesWithVerificationUseCase);
  container.bind<IVerifyCompanyUseCase>(TYPES.VerifyCompanyUseCase).to(VerifyCompanyUseCase);
  container.bind<IGetPendingCompaniesUseCase>(TYPES.GetPendingCompaniesUseCase).to(GetPendingCompaniesUseCase);
  container.bind<IGetCompanyByIdUseCase>(TYPES.GetCompanyByIdUseCase).to(GetCompanyByIdUseCase);
  container.bind<IAdminGetAllJobsUseCase>(TYPES.AdminGetAllJobsUseCase).to(GetAllJobsUseCase);
  container.bind<IAdminGetJobByIdUseCase>(TYPES.AdminGetJobByIdUseCase).to(AdminGetJobByIdUseCase);
  container.bind<IAdminUpdateJobStatusUseCase>(TYPES.AdminUpdateJobStatusUseCase).to(AdminUpdateJobStatusUseCase);
  container.bind<IAdminDeleteJobUseCase>(TYPES.AdminDeleteJobUseCase).to(AdminDeleteJobUseCase);
  container.bind<IAdminGetJobStatsUseCase>(TYPES.AdminGetJobStatsUseCase).to(AdminGetJobStatsUseCase);
  container.bind<ICreateJobCategoryUseCase>(TYPES.CreateJobCategoryUseCase).to(CreateJobCategoryUseCase);
  container.bind<IGetAllJobCategoriesUseCase>(TYPES.GetAllJobCategoriesUseCase).to(GetAllJobCategoriesUseCase);
  container.bind<IGetJobCategoryByIdUseCase>(TYPES.GetJobCategoryByIdUseCase).to(GetJobCategoryByIdUseCase);
  container.bind<IUpdateJobCategoryUseCase>(TYPES.UpdateJobCategoryUseCase).to(UpdateJobCategoryUseCase);
  container.bind<IDeleteJobCategoryUseCase>(TYPES.DeleteJobCategoryUseCase).to(DeleteJobCategoryUseCase);
  container.bind<ICreateSkillUseCase>(TYPES.CreateSkillUseCase).to(CreateSkillUseCase);
  container.bind<IGetAllSkillsUseCase>(TYPES.GetAllSkillsUseCase).to(GetAllSkillsUseCase);
  container.bind<IGetSkillByIdUseCase>(TYPES.GetSkillByIdUseCase).to(GetSkillByIdUseCase);
  container.bind<IUpdateSkillUseCase>(TYPES.UpdateSkillUseCase).to(UpdateSkillUseCase);
  container.bind<IDeleteSkillUseCase>(TYPES.DeleteSkillUseCase).to(DeleteSkillUseCase);
  container.bind<ICreateJobRoleUseCase>(TYPES.CreateJobRoleUseCase).to(CreateJobRoleUseCase);
  container.bind<IGetAllJobRolesUseCase>(TYPES.GetAllJobRolesUseCase).to(GetAllJobRolesUseCase);
  container.bind<IGetJobRoleByIdUseCase>(TYPES.GetJobRoleByIdUseCase).to(GetJobRoleByIdUseCase);
  container.bind<IUpdateJobRoleUseCase>(TYPES.UpdateJobRoleUseCase).to(UpdateJobRoleUseCase);
  container.bind<IDeleteJobRoleUseCase>(TYPES.DeleteJobRoleUseCase).to(DeleteJobRoleUseCase);
  container.bind<ICreateSubscriptionPlanUseCase>(TYPES.CreateSubscriptionPlanUseCase).to(CreateSubscriptionPlanUseCase);
  container.bind<IGetAllSubscriptionPlansUseCase>(TYPES.GetAllSubscriptionPlansUseCase).to(GetAllSubscriptionPlansUseCase);
  container.bind<IGetSubscriptionPlanByIdUseCase>(TYPES.GetSubscriptionPlanByIdUseCase).to(GetSubscriptionPlanByIdUseCase);
  container.bind<IUpdateSubscriptionPlanUseCase>(TYPES.UpdateSubscriptionPlanUseCase).to(UpdateSubscriptionPlanUseCase);
  container.bind<IGetAllPaymentOrdersUseCase>(TYPES.GetAllPaymentOrdersUseCase).to(GetAllPaymentOrdersUseCase);
  container.bind<IGetAdminDashboardStatsUseCase>(TYPES.GetAdminDashboardStatsUseCase).to(GetAdminDashboardStatsUseCase);

  container.bind<AdminUserController>(TYPES.AdminUserController).to(AdminUserController);
  container.bind<AdminCompanyController>(TYPES.AdminCompanyController).to(AdminCompanyController);
  container.bind<AdminJobController>(TYPES.AdminJobController).to(AdminJobController);
  container.bind<AdminJobCategoryController>(TYPES.AdminJobCategoryController).to(AdminJobCategoryController);
  container.bind<AdminSkillController>(TYPES.AdminSkillController).to(AdminSkillController);
  container.bind<AdminJobRoleController>(TYPES.AdminJobRoleController).to(AdminJobRoleController);
  container.bind<AdminSubscriptionPlanController>(TYPES.AdminSubscriptionPlanController).to(AdminSubscriptionPlanController);
  container.bind<AdminPaymentOrderController>(TYPES.AdminPaymentOrderController).to(AdminPaymentOrderController);
  container.bind<AdminDashboardController>(TYPES.AdminDashboardController).to(AdminDashboardController);
}
