import { Container } from 'inversify';
import { TYPES } from 'src/shared/constants/types';

import { IUserRepository } from 'src/domain/interfaces/repositories/user/IUserRepository';
import { UserRepository } from 'src/infrastructure/persistence/mongodb/repositories/user.repository';
import { IConversationRepository } from 'src/domain/interfaces/repositories/chat/IConversationRepository';
import { ConversationRepository } from 'src/infrastructure/persistence/mongodb/repositories/conversation.repository';
import { IMessageRepository } from 'src/domain/interfaces/repositories/chat/IMessageRepository';
import { ChatMessageRepository } from 'src/infrastructure/persistence/mongodb/repositories/chat-message.repository';
import { CompanyProfileRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-profile.repository';
import { CompanyVerificationRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-verification.repository';
import { JobPostingRepository } from 'src/infrastructure/persistence/mongodb/repositories/job-posting.repository';
import { JobCategoryRepository } from 'src/infrastructure/persistence/mongodb/repositories/job-category.repository';
import { SkillRepository } from 'src/infrastructure/persistence/mongodb/repositories/skill.repository';
import { JobRoleRepository } from 'src/infrastructure/persistence/mongodb/repositories/job-role.repository';
import { SubscriptionPlanRepository } from 'src/infrastructure/persistence/mongodb/repositories/subscription-plan.repository';
import { CompanySubscriptionRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-subscription.repository';
import { PaymentOrderRepository } from 'src/infrastructure/persistence/mongodb/repositories/payment-order.repository';
import { SeekerProfileRepository } from 'src/infrastructure/persistence/mongodb/repositories/seeker-profile.repository';
import { PriceHistoryRepository } from 'src/infrastructure/persistence/mongodb/repositories/price-history.repository';
import { CompanyContactRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-contact.repository';
import { CompanyOfficeLocationRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-office-location.repository';
import { CompanyTechStackRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-tech-stack.repository';
import { CompanyBenefitsRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-benefits.repository';
import { CompanyWorkplacePicturesRepository } from 'src/infrastructure/persistence/mongodb/repositories/company-workplace-pictures.repository';
import { ICompanyProfileRepository } from 'src/domain/interfaces/repositories/company/ICompanyProfileRepository';
import { ICompanyVerificationRepository } from 'src/domain/interfaces/repositories/company/ICompanyVerificationRepository';
import { IJobPostingRepository } from 'src/domain/interfaces/repositories/job/IJobPostingRepository';
import { ISeekerProfileRepository } from 'src/domain/interfaces/repositories/seeker/ISeekerProfileRepository';
import { IPaymentOrderRepository } from 'src/domain/interfaces/repositories/payment/IPaymentOrderRepository';
import { ISubscriptionPlanRepository } from 'src/domain/interfaces/repositories/subscription-plan/ISubscriptionPlanRepository';
import { ICompanySubscriptionRepository } from 'src/domain/interfaces/repositories/subscription/ICompanySubscriptionRepository';
import { IPriceHistoryRepository } from 'src/domain/interfaces/repositories/price-history/IPriceHistoryRepository';
import { ICompanyContactRepository } from 'src/domain/interfaces/repositories/company/ICompanyContactRepository';
import { ICompanyOfficeLocationRepository } from 'src/domain/interfaces/repositories/company/ICompanyOfficeLocationRepository';
import { ICompanyTechStackRepository } from 'src/domain/interfaces/repositories/company/ICompanyTechStackRepository';
import { ICompanyBenefitsRepository } from 'src/domain/interfaces/repositories/company/ICompanyBenefitsRepository';
import { ICompanyWorkplacePicturesRepository } from 'src/domain/interfaces/repositories/company/ICompanyWorkplacePicturesRepository';
import { IJobApplicationRepository } from 'src/domain/interfaces/repositories/job-application/IJobApplicationRepository';
import { JobApplicationRepository } from 'src/infrastructure/persistence/mongodb/repositories/job-application.repository';
import { ISeekerExperienceRepository } from 'src/domain/interfaces/repositories/seeker/ISeekerExperienceRepository';
import { SeekerExperienceRepository } from 'src/infrastructure/persistence/mongodb/repositories/seeker-experience.repository';
import { ISeekerEducationRepository } from 'src/domain/interfaces/repositories/seeker/ISeekerEducationRepository';
import { SeekerEducationRepository } from 'src/infrastructure/persistence/mongodb/repositories/seeker-education.repository';
import { IATSInterviewRepository } from 'src/domain/interfaces/repositories/ats/IATSInterviewRepository';
import { ATSInterviewRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-interview.repository';
import { IATSTechnicalTaskRepository } from 'src/domain/interfaces/repositories/ats/IATSTechnicalTaskRepository';
import { ATSTechnicalTaskRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-technical-task.repository';
import { IATSOfferRepository } from 'src/domain/interfaces/repositories/ats/IATSOfferRepository';
import { ATSOfferRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-offer.repository';
import { IATSCompensationRepository } from 'src/domain/interfaces/repositories/ats/IATSCompensationRepository';
import { ATSCompensationRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-compensation.repository';
import { IATSCompensationMeetingRepository } from 'src/domain/interfaces/repositories/ats/IATSCompensationMeetingRepository';
import { ATSCompensationMeetingRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-compensation-meeting.repository';
import { IATSCommentRepository } from 'src/domain/interfaces/repositories/ats/IATSCommentRepository';
import { ATSCommentRepository } from 'src/infrastructure/persistence/mongodb/repositories/ats-comment.repository';
import { IJobCategoryRepository } from 'src/domain/interfaces/repositories/job-category/IJobCategoryRepository';
import { ISkillRepository } from 'src/domain/interfaces/repositories/skill/ISkillRepository';
import { IJobRoleRepository } from 'src/domain/interfaces/repositories/job-role/IJobRoleRepository';

import { IS3Service } from 'src/domain/interfaces/services/IS3Service';
import { S3Service } from 'src/infrastructure/external-services/s3/s3.service';
import { ILogger } from 'src/domain/interfaces/services/ILogger';
import { LoggerService } from 'src/infrastructure/services/logger.service';
import { IAtsService } from 'src/domain/interfaces/services/IAtsService';
import { AtsService } from 'src/infrastructure/external-services/ai/ats-groq.service';
import { IResumeParserService } from 'src/domain/interfaces/services/IResumeParserService';
import { ResumeParserService } from 'src/infrastructure/services/resume-parser.service';
import { IFileUploadService } from 'src/domain/interfaces/services/IFileUploadService';
import { FileUploadService } from 'src/application/services/file-upload.service';

export function registerCoreDi(container: Container): void {
  container.bind<IUserRepository>(TYPES.UserRepository).to(UserRepository);
  container.bind<IConversationRepository>(TYPES.ConversationRepository).to(ConversationRepository);
  container.bind<IMessageRepository>(TYPES.ChatMessageRepository).to(ChatMessageRepository);
  container.bind<ICompanyProfileRepository>(TYPES.CompanyProfileRepository).to(CompanyProfileRepository);
  container.bind<ICompanyVerificationRepository>(TYPES.CompanyVerificationRepository).to(CompanyVerificationRepository);
  container.bind<IJobPostingRepository>(TYPES.JobPostingRepository).to(JobPostingRepository);
  container.bind<ISeekerProfileRepository>(TYPES.SeekerProfileRepository).to(SeekerProfileRepository);
  container.bind<IPaymentOrderRepository>(TYPES.PaymentOrderRepository).to(PaymentOrderRepository);
  container.bind<ISubscriptionPlanRepository>(TYPES.SubscriptionPlanRepository).to(SubscriptionPlanRepository);
  container.bind<ICompanySubscriptionRepository>(TYPES.CompanySubscriptionRepository).to(CompanySubscriptionRepository);
  container.bind<IPriceHistoryRepository>(TYPES.PriceHistoryRepository).to(PriceHistoryRepository);
  container.bind<ICompanyContactRepository>(TYPES.CompanyContactRepository).to(CompanyContactRepository);
  container.bind<ICompanyOfficeLocationRepository>(TYPES.CompanyOfficeLocationRepository).to(CompanyOfficeLocationRepository);
  container.bind<ICompanyTechStackRepository>(TYPES.CompanyTechStackRepository).to(CompanyTechStackRepository);
  container.bind<ICompanyBenefitsRepository>(TYPES.CompanyBenefitsRepository).to(CompanyBenefitsRepository);
  container.bind<ICompanyWorkplacePicturesRepository>(TYPES.CompanyWorkplacePicturesRepository).to(CompanyWorkplacePicturesRepository);

  container.bind<IJobApplicationRepository>(TYPES.JobApplicationRepository).to(JobApplicationRepository);
  container.bind<ISeekerExperienceRepository>(TYPES.SeekerExperienceRepository).to(SeekerExperienceRepository);
  container.bind<ISeekerEducationRepository>(TYPES.SeekerEducationRepository).to(SeekerEducationRepository);
  container.bind<IATSInterviewRepository>(TYPES.ATSInterviewRepository).to(ATSInterviewRepository);
  container.bind<IATSTechnicalTaskRepository>(TYPES.ATSTechnicalTaskRepository).to(ATSTechnicalTaskRepository);
  container.bind<IATSOfferRepository>(TYPES.ATSOfferRepository).to(ATSOfferRepository);
  container.bind<IATSCompensationRepository>(TYPES.ATSCompensationRepository).to(ATSCompensationRepository);
  container.bind<IATSCompensationMeetingRepository>(TYPES.ATSCompensationMeetingRepository).to(ATSCompensationMeetingRepository);
  container.bind<IATSCommentRepository>(TYPES.ATSCommentRepository).to(ATSCommentRepository);

  container.bind<IJobCategoryRepository>(TYPES.JobCategoryRepository).to(JobCategoryRepository);
  container.bind<ISkillRepository>(TYPES.SkillRepository).to(SkillRepository);
  container.bind<IJobRoleRepository>(TYPES.JobRoleRepository).to(JobRoleRepository);

  container.bind<IS3Service>(TYPES.S3Service).to(S3Service);
  container.bind<ILogger>(TYPES.LoggerService).to(LoggerService);
  container.bind<IAtsService>(TYPES.AtsService).to(AtsService);
  container.bind<IResumeParserService>(TYPES.ResumeParserService).to(ResumeParserService);
  container.bind<IFileUploadService>(TYPES.FileUploadService).to(FileUploadService);
}
