import { Container } from 'inversify';
import { TYPES } from 'src/shared/constants/types';

import { ICreateSeekerProfileUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/info/ICreateSeekerProfileUseCase';
import { CreateSeekerProfileUseCase } from 'src/application/use-cases/seeker/profile/info/create-seeker-profile.use-case';
import { IUpdateSeekerProfileUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/info/IUpdateSeekerProfileUseCase';
import { UpdateSeekerProfileUseCase } from 'src/application/use-cases/seeker/profile/info/update-seeker-profile.use-case';
import { IGetSeekerProfileUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/info/IGetSeekerProfileUseCase';
import { GetSeekerProfileUseCase } from 'src/application/use-cases/seeker/profile/info/get-seeker-profile.use-case';
import { IAddExperienceUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/experience/IAddExperienceUseCase';
import { AddExperienceUseCase } from 'src/application/use-cases/seeker/profile/experience/add-experience.use-case';
import { IGetExperiencesUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/experience/IGetExperiencesUseCase';
import { GetExperiencesUseCase } from 'src/application/use-cases/seeker/profile/experience/get-experiences.use-case';
import { IUpdateExperienceUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/experience/IUpdateExperienceUseCase';
import { UpdateExperienceUseCase } from 'src/application/use-cases/seeker/profile/experience/update-experience.use-case';
import { IRemoveExperienceUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/experience/IRemoveExperienceUseCase';
import { RemoveExperienceUseCase } from 'src/application/use-cases/seeker/profile/experience/remove-experience.use-case';
import { IAddEducationUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/education/IAddEducationUseCase';
import { AddEducationUseCase } from 'src/application/use-cases/seeker/profile/education/add-education.use-case';
import { IGetEducationUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/education/IGetEducationUseCase';
import { GetEducationUseCase } from 'src/application/use-cases/seeker/profile/education/get-education.use-case';
import { IUpdateEducationUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/education/IUpdateEducationUseCase';
import { UpdateEducationUseCase } from 'src/application/use-cases/seeker/profile/education/update-education.use-case';
import { IRemoveEducationUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/education/IRemoveEducationUseCase';
import { RemoveEducationUseCase } from 'src/application/use-cases/seeker/profile/education/remove-education.use-case';
import { IUpdateSkillsUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/skills/IUpdateSkillsUseCase';
import { UpdateSkillsUseCase } from 'src/application/use-cases/seeker/profile/skills/update-skills.use-case';
import { IUpdateLanguagesUseCase } from 'src/domain/interfaces/use-cases/seeker/profile/languages/IUpdateLanguagesUseCase';
import { UpdateLanguagesUseCase } from 'src/application/use-cases/seeker/profile/languages/update-languages.use-case';
import { IUploadResumeUseCase } from 'src/domain/interfaces/use-cases/seeker/media/IUploadResumeUseCase';
import { UploadResumeUseCase } from 'src/application/use-cases/seeker/media/upload-resume.use-case';
import { IRemoveResumeUseCase } from 'src/domain/interfaces/use-cases/seeker/media/IRemoveResumeUseCase';
import { RemoveResumeUseCase } from 'src/application/use-cases/seeker/media/remove-resume.use-case';
import { IUploadAvatarUseCase } from 'src/domain/interfaces/use-cases/seeker/media/IUploadAvatarUseCase';
import { UploadAvatarUseCase } from 'src/application/use-cases/seeker/media/upload-avatar.use-case';
import { IUploadBannerUseCase } from 'src/domain/interfaces/use-cases/seeker/media/IUploadBannerUseCase';
import { UploadBannerUseCase } from 'src/application/use-cases/seeker/media/upload-banner.use-case';

import { ICalculateATSScoreUseCase, CalculateATSScoreUseCase } from 'src/application/use-cases/seeker/applications/calculate-ats-score.use-case';
import { ICreateJobApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/ICreateJobApplicationUseCase';
import { CreateJobApplicationUseCase } from 'src/application/use-cases/seeker/applications/create-job-application.use-case';
import { IGetApplicationsBySeekerUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetApplicationsBySeekerUseCase';
import { GetApplicationsBySeekerUseCase } from 'src/application/use-cases/seeker/applications/get-applications-by-seeker.use-case';
import { IGetSeekerApplicationDetailsUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetSeekerApplicationDetailsUseCase';
import { GetSeekerApplicationDetailsUseCase } from 'src/application/use-cases/seeker/applications/get-seeker-application-details.use-case';
import { IAnalyzeResumeUseCase } from 'src/domain/interfaces/use-cases/seeker/score-checker/IAnalyzeResumeUseCase';
import { AnalyzeResumeUseCase } from 'src/application/use-cases/seeker/score-checker/analyze-resume.use-case';
import { IGetInterviewsByApplicationUseCase as ISeekerGetInterviewsByApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetInterviewsByApplicationUseCase';
import { GetInterviewsByApplicationUseCase as SeekerGetInterviewsByApplicationUseCase } from 'src/application/use-cases/seeker/applications/get-interviews-by-application.use-case';
import { IGetTechnicalTasksByApplicationUseCase as ISeekerGetTechnicalTasksByApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetTechnicalTasksByApplicationUseCase';
import { GetTechnicalTasksByApplicationUseCase as SeekerGetTechnicalTasksByApplicationUseCase } from 'src/application/use-cases/seeker/applications/get-technical-tasks-by-application.use-case';
import { ISubmitTechnicalTaskUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/ISubmitTechnicalTaskUseCase';
import { SubmitTechnicalTaskUseCase } from 'src/application/use-cases/seeker/applications/submit-technical-task.use-case';
import { IGetOffersByApplicationUseCase as ISeekerGetOffersByApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetOffersByApplicationUseCase';
import { GetOffersByApplicationUseCase as SeekerGetOffersByApplicationUseCase } from 'src/application/use-cases/seeker/applications/get-offers-by-application.use-case';
import { IGetCompensationByApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetCompensationByApplicationUseCase';
import { GetCompensationByApplicationUseCase } from 'src/application/use-cases/seeker/applications/get-compensation-by-application.use-case';
import { IGetCompensationMeetingsByApplicationUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IGetCompensationMeetingsByApplicationUseCase';
import { GetCompensationMeetingsByApplicationUseCase } from 'src/application/use-cases/seeker/applications/get-compensation-meetings-by-application.use-case';
import { IUpdateOfferStatusUseCase as ISeekerUpdateOfferStatusUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IUpdateOfferStatusUseCase';
import { UpdateOfferStatusUseCase as SeekerUpdateOfferStatusUseCase } from 'src/application/use-cases/application/offer/update-offer-status.use-case';
import { IUploadSignedOfferDocumentUseCase } from 'src/domain/interfaces/use-cases/seeker/applications/IUploadSignedOfferDocumentUseCase';
import { UploadSignedOfferDocumentUseCase } from 'src/application/use-cases/seeker/applications/upload-signed-offer-document.use-case';
import { IUpdateApplicationSubStageUseCase } from 'src/domain/interfaces/use-cases/application/pipeline/IUpdateApplicationSubStageUseCase';
import { UpdateApplicationSubStageUseCase } from 'src/application/use-cases/application/pipeline/update-application-sub-stage.use-case';

import { SeekerProfileController } from 'src/presentation/controllers/seeker/profile/seeker-profile.controller';
import { SeekerJobApplicationController } from 'src/presentation/controllers/seeker/applications/job-application.controller';

export function registerSeekerDi(container: Container): void {
  container.bind<ICreateSeekerProfileUseCase>(TYPES.CreateSeekerProfileUseCase).to(CreateSeekerProfileUseCase);
  container.bind<IUpdateSeekerProfileUseCase>(TYPES.UpdateSeekerProfileUseCase).to(UpdateSeekerProfileUseCase);
  container.bind<IGetSeekerProfileUseCase>(TYPES.GetSeekerProfileUseCase).to(GetSeekerProfileUseCase);
  container.bind<IAddExperienceUseCase>(TYPES.AddExperienceUseCase).to(AddExperienceUseCase);
  container.bind<IGetExperiencesUseCase>(TYPES.GetExperiencesUseCase).to(GetExperiencesUseCase);
  container.bind<IUpdateExperienceUseCase>(TYPES.UpdateExperienceUseCase).to(UpdateExperienceUseCase);
  container.bind<IRemoveExperienceUseCase>(TYPES.RemoveExperienceUseCase).to(RemoveExperienceUseCase);
  container.bind<IAddEducationUseCase>(TYPES.AddEducationUseCase).to(AddEducationUseCase);
  container.bind<IGetEducationUseCase>(TYPES.GetEducationUseCase).to(GetEducationUseCase);
  container.bind<IUpdateEducationUseCase>(TYPES.UpdateEducationUseCase).to(UpdateEducationUseCase);
  container.bind<IRemoveEducationUseCase>(TYPES.RemoveEducationUseCase).to(RemoveEducationUseCase);
  container.bind<IUpdateSkillsUseCase>(TYPES.UpdateSkillsUseCase).to(UpdateSkillsUseCase);
  container.bind<IUpdateLanguagesUseCase>(TYPES.UpdateLanguagesUseCase).to(UpdateLanguagesUseCase);
  container.bind<IUploadResumeUseCase>(TYPES.UploadResumeUseCase).to(UploadResumeUseCase);
  container.bind<IRemoveResumeUseCase>(TYPES.RemoveResumeUseCase).to(RemoveResumeUseCase);
  container.bind<IUploadAvatarUseCase>(TYPES.UploadAvatarUseCase).to(UploadAvatarUseCase);
  container.bind<IUploadBannerUseCase>(TYPES.UploadBannerUseCase).to(UploadBannerUseCase);
  container.bind<ICalculateATSScoreUseCase>(TYPES.CalculateATSScoreUseCase).to(CalculateATSScoreUseCase);
  container.bind<ICreateJobApplicationUseCase>(TYPES.CreateJobApplicationUseCase).to(CreateJobApplicationUseCase);
  container.bind<IGetApplicationsBySeekerUseCase>(TYPES.GetApplicationsBySeekerUseCase).to(GetApplicationsBySeekerUseCase);
  container.bind<IGetSeekerApplicationDetailsUseCase>(TYPES.GetSeekerApplicationDetailsUseCase).to(GetSeekerApplicationDetailsUseCase);
  container.bind<IAnalyzeResumeUseCase>(TYPES.AnalyzeResumeUseCase).to(AnalyzeResumeUseCase);
  container.bind<ISeekerGetInterviewsByApplicationUseCase>(TYPES.GetInterviewsByApplicationUseCase).to(SeekerGetInterviewsByApplicationUseCase);
  container.bind<ISeekerGetTechnicalTasksByApplicationUseCase>(TYPES.GetTechnicalTasksByApplicationUseCase).to(SeekerGetTechnicalTasksByApplicationUseCase);
  container.bind<ISubmitTechnicalTaskUseCase>(TYPES.SubmitTechnicalTaskUseCase).to(SubmitTechnicalTaskUseCase);
  container.bind<ISeekerGetOffersByApplicationUseCase>(TYPES.GetOffersByApplicationUseCase).to(SeekerGetOffersByApplicationUseCase);
  container.bind<IGetCompensationByApplicationUseCase>(TYPES.GetCompensationByApplicationUseCase).to(GetCompensationByApplicationUseCase);
  container.bind<IGetCompensationMeetingsByApplicationUseCase>(TYPES.GetCompensationMeetingsByApplicationUseCase).to(GetCompensationMeetingsByApplicationUseCase);
  container.bind<ISeekerUpdateOfferStatusUseCase>(TYPES.UpdateOfferStatusUseCase).to(SeekerUpdateOfferStatusUseCase);
  container.bind<IUploadSignedOfferDocumentUseCase>(TYPES.UploadSignedOfferDocumentUseCase).to(UploadSignedOfferDocumentUseCase);
  container.bind<IUpdateApplicationSubStageUseCase>(TYPES.UpdateApplicationSubStageUseCase).to(UpdateApplicationSubStageUseCase);

  container.bind<SeekerProfileController>(TYPES.SeekerProfileController).to(SeekerProfileController);
  container.bind<SeekerJobApplicationController>(TYPES.SeekerJobApplicationController).to(SeekerJobApplicationController);
}
