import { Container } from 'inversify';
import { TYPES } from 'src/shared/constants/types';

import { IScheduleInterviewUseCase } from 'src/domain/interfaces/use-cases/application/interview/IScheduleInterviewUseCase';
import { IUpdateInterviewUseCase } from 'src/domain/interfaces/use-cases/application/interview/IUpdateInterviewUseCase';
import { IGetInterviewsByApplicationUseCase as IATSGetInterviewsByApplicationUseCase } from 'src/domain/interfaces/use-cases/application/interview/IGetInterviewsByApplicationUseCase';
import { IAssignTechnicalTaskUseCase } from 'src/domain/interfaces/use-cases/application/task/IAssignTechnicalTaskUseCase';
import { IUpdateTechnicalTaskUseCase } from 'src/domain/interfaces/use-cases/application/task/IUpdateTechnicalTaskUseCase';
import { IDeleteTechnicalTaskUseCase } from 'src/domain/interfaces/use-cases/application/task/IDeleteTechnicalTaskUseCase';
import { IGetTechnicalTasksByApplicationUseCase as IATSGetTechnicalTasksByApplicationUseCase } from 'src/domain/interfaces/use-cases/application/task/IGetTechnicalTasksByApplicationUseCase';
import { IUploadOfferUseCase as IATSUploadOfferUseCase } from 'src/domain/interfaces/use-cases/application/offer/IUploadOfferUseCase';
import { IUpdateOfferStatusUseCase as IATSUpdateOfferStatusUseCase } from 'src/domain/interfaces/use-cases/application/offer/IUpdateOfferStatusUseCase';
import { IGetOffersByApplicationUseCase as IATSGetOffersByApplicationUseCase } from 'src/domain/interfaces/use-cases/application/offer/IGetOffersByApplicationUseCase';
import { IAddCommentUseCase } from 'src/domain/interfaces/use-cases/application/comments/IAddCommentUseCase';
import { IGetCommentsByApplicationUseCase } from 'src/domain/interfaces/use-cases/application/comments/IGetCommentsByApplicationUseCase';
import { IMoveApplicationStageUseCase } from 'src/domain/interfaces/use-cases/application/pipeline/IMoveApplicationStageUseCase';
import { IGetJobATSPipelineUseCase } from 'src/domain/interfaces/use-cases/application/pipeline/IGetJobATSPipelineUseCase';
import { IGetJobApplicationsForKanbanUseCase } from 'src/domain/interfaces/use-cases/application/pipeline/IGetJobApplicationsForKanbanUseCase';
import { IInitiateCompensationUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IInitiateCompensationUseCase';
import { IUpdateCompensationUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IUpdateCompensationUseCase';
import { IGetCompensationUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IGetCompensationUseCase';
import { IScheduleCompensationMeetingUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IScheduleCompensationMeetingUseCase';
import { IGetCompensationMeetingsUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IGetCompensationMeetingsUseCase';
import { IUpdateCompensationMeetingStatusUseCase } from 'src/domain/interfaces/use-cases/application/compensation/IUpdateCompensationMeetingStatusUseCase';
import { IGetCompanyProfileUseCase } from 'src/domain/interfaces/use-cases/company/profile/info/IGetCompanyProfileUseCase';
import { IGetCompanyIdByUserIdUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetCompanyIdByUserIdUseCase';

import { ScheduleInterviewUseCase } from 'src/application/use-cases/application/interview/schedule-interview.use-case';
import { UpdateInterviewUseCase } from 'src/application/use-cases/application/interview/update-interview.use-case';
import { GetInterviewsByApplicationUseCase as ATSGetInterviewsByApplicationUseCase } from 'src/application/use-cases/application/interview/get-interviews-by-application.use-case';
import { AssignTechnicalTaskUseCase } from 'src/application/use-cases/application/task/assign-technical-task.use-case';
import { UpdateTechnicalTaskUseCase } from 'src/application/use-cases/application/task/update-technical-task.use-case';
import { DeleteTechnicalTaskUseCase } from 'src/application/use-cases/application/task/delete-technical-task.use-case';
import { GetTechnicalTasksByApplicationUseCase as ATSGetTechnicalTasksByApplicationUseCase } from 'src/application/use-cases/application/task/get-technical-tasks-by-application.use-case';
import { UploadOfferUseCase as ATSUploadOfferUseCase } from 'src/application/use-cases/application/offer/upload-offer.use-case';
import { UpdateOfferStatusUseCase as ATSUpdateOfferStatusUseCase } from 'src/application/use-cases/application/offer/update-offer-status.use-case';
import { GetOffersByApplicationUseCase as ATSGetOffersByApplicationUseCase } from 'src/application/use-cases/application/offer/get-offers-by-application.use-case';
import { AddCommentUseCase } from 'src/application/use-cases/application/comments/add-comment.use-case';
import { GetCommentsByApplicationUseCase } from 'src/application/use-cases/application/comments/get-comments-by-application.use-case';
import { MoveApplicationStageUseCase } from 'src/application/use-cases/application/pipeline/move-application-stage.use-case';
import { GetJobATSPipelineUseCase } from 'src/application/use-cases/application/pipeline/get-job-ats-pipeline.use-case';
import { GetJobApplicationsForKanbanUseCase } from 'src/application/use-cases/application/pipeline/get-job-applications-for-kanban.use-case';
import { InitiateCompensationUseCase } from 'src/application/use-cases/application/compensation/initiate-compensation.use-case';
import { UpdateCompensationUseCase } from 'src/application/use-cases/application/compensation/update-compensation.use-case';
import { GetCompensationUseCase } from 'src/application/use-cases/application/compensation/get-compensation.use-case';
import { ScheduleCompensationMeetingUseCase } from 'src/application/use-cases/application/compensation/schedule-compensation-meeting.use-case';
import { GetCompensationMeetingsUseCase } from 'src/application/use-cases/application/compensation/get-compensation-meetings.use-case';
import { UpdateCompensationMeetingStatusUseCase } from 'src/application/use-cases/application/compensation/update-compensation-meeting-status.use-case';
import { GetCompanyProfileUseCase } from 'src/application/use-cases/company/profile/info/get-company-profile.use-case';
import { GetCompanyIdByUserIdUseCase } from 'src/application/use-cases/admin/companies/get-company-id-by-user-id.use-case';

import { ATSPipelineController } from 'src/presentation/controllers/ats/pipeline/ats-pipeline.controller';
import { ATSInterviewController } from 'src/presentation/controllers/ats/evaluation/ats-interview.controller';
import { ATSTechnicalTaskController } from 'src/presentation/controllers/ats/evaluation/ats-technical-task.controller';
import { ATSOfferController } from 'src/presentation/controllers/ats/offer/ats-offer.controller';
import { ATSCommentController } from 'src/presentation/controllers/ats/comments/ats-comment.controller';
import { ATSCompensationController } from 'src/presentation/controllers/ats/offer/ats-compensation.controller';

export function registerAtsDi(container: Container): void {
  container.bind<IScheduleInterviewUseCase>(TYPES.ATS_ScheduleInterviewUseCase).to(ScheduleInterviewUseCase);
  container.bind<IGetCompanyProfileUseCase>(TYPES.GetCompanyProfileUseCase).to(GetCompanyProfileUseCase);
  container.bind<IGetCompanyIdByUserIdUseCase>(TYPES.GetCompanyIdByUserIdUseCase).to(GetCompanyIdByUserIdUseCase);
  container.bind<IUpdateInterviewUseCase>(TYPES.ATS_UpdateInterviewUseCase).to(UpdateInterviewUseCase);
  container.bind<IATSGetInterviewsByApplicationUseCase>(TYPES.ATS_GetInterviewsByApplicationUseCase).to(ATSGetInterviewsByApplicationUseCase);
  container.bind<IAssignTechnicalTaskUseCase>(TYPES.ATS_AssignTechnicalTaskUseCase).to(AssignTechnicalTaskUseCase);
  container.bind<IUpdateTechnicalTaskUseCase>(TYPES.ATS_UpdateTechnicalTaskUseCase).to(UpdateTechnicalTaskUseCase);
  container.bind<IDeleteTechnicalTaskUseCase>(TYPES.ATS_DeleteTechnicalTaskUseCase).to(DeleteTechnicalTaskUseCase);
  container.bind<IATSGetTechnicalTasksByApplicationUseCase>(TYPES.ATS_GetTechnicalTasksByApplicationUseCase).to(ATSGetTechnicalTasksByApplicationUseCase);
  container.bind<IATSUploadOfferUseCase>(TYPES.ATS_UploadOfferUseCase).to(ATSUploadOfferUseCase);
  container.bind<IATSUpdateOfferStatusUseCase>(TYPES.ATS_UpdateOfferStatusUseCase).to(ATSUpdateOfferStatusUseCase);
  container.bind<IATSGetOffersByApplicationUseCase>(TYPES.ATS_GetOffersByApplicationUseCase).to(ATSGetOffersByApplicationUseCase);
  container.bind<IAddCommentUseCase>(TYPES.ATS_AddCommentUseCase).to(AddCommentUseCase);
  container.bind<IGetCommentsByApplicationUseCase>(TYPES.ATS_GetCommentsByApplicationUseCase).to(GetCommentsByApplicationUseCase);
  container.bind<IMoveApplicationStageUseCase>(TYPES.ATS_MoveApplicationStageUseCase).to(MoveApplicationStageUseCase);
  container.bind<IGetJobATSPipelineUseCase>(TYPES.ATS_GetJobATSPipelineUseCase).to(GetJobATSPipelineUseCase);
  container.bind<IGetJobApplicationsForKanbanUseCase>(TYPES.ATS_GetJobApplicationsForKanbanUseCase).to(GetJobApplicationsForKanbanUseCase);
  container.bind<IInitiateCompensationUseCase>(TYPES.ATS_InitiateCompensationUseCase).to(InitiateCompensationUseCase);
  container.bind<IUpdateCompensationUseCase>(TYPES.ATS_UpdateCompensationUseCase).to(UpdateCompensationUseCase);
  container.bind<IGetCompensationUseCase>(TYPES.ATS_GetCompensationUseCase).to(GetCompensationUseCase);
  container.bind<IScheduleCompensationMeetingUseCase>(TYPES.ATS_ScheduleCompensationMeetingUseCase).to(ScheduleCompensationMeetingUseCase);
  container.bind<IGetCompensationMeetingsUseCase>(TYPES.ATS_GetCompensationMeetingsUseCase).to(GetCompensationMeetingsUseCase);
  container.bind<IUpdateCompensationMeetingStatusUseCase>(TYPES.ATS_UpdateCompensationMeetingStatusUseCase).to(UpdateCompensationMeetingStatusUseCase);

  container.bind<ATSInterviewController>(TYPES.ATSInterviewController).to(ATSInterviewController);
  container.bind<ATSTechnicalTaskController>(TYPES.ATSTechnicalTaskController).to(ATSTechnicalTaskController);
  container.bind<ATSOfferController>(TYPES.ATSOfferController).to(ATSOfferController);
  container.bind<ATSCommentController>(TYPES.ATSCommentController).to(ATSCommentController);
  container.bind<ATSCompensationController>(TYPES.ATSCompensationController).to(ATSCompensationController);
  container.bind<ATSPipelineController>(TYPES.ATSPipelineController).to(ATSPipelineController);
}
