import { Container } from 'inversify';
import { TYPES } from 'src/shared/constants/types';

import { ICreateCompanyProfileUseCase } from 'src/domain/interfaces/use-cases/company/profile/info/ICreateCompanyProfileUseCase';
import { CreateCompanyProfileUseCase } from 'src/application/use-cases/company/profile/info/create-company-profile.use-case';
import { ICreateCompanyProfileFromDtoUseCase } from 'src/domain/interfaces/use-cases/company/profile/info/ICreateCompanyProfileFromDtoUseCase';
import { CreateCompanyProfileFromDtoUseCase } from 'src/application/use-cases/company/profile/info/create-company-profile-from-dto.use-case';
import { IUpdateCompanyProfileUseCase } from 'src/domain/interfaces/use-cases/company/profile/info/IUpdateCompanyProfileUseCase';
import { UpdateCompanyProfileUseCase } from 'src/application/use-cases/company/profile/info/update-company-profile.use-case';
import { IGetCompanyProfileWithJobPostingsUseCase } from 'src/domain/interfaces/use-cases/admin/companies/IGetCompanyProfileWithJobPostingsUseCase';
import { GetCompanyProfileWithJobPostingsUseCase } from 'src/application/use-cases/admin/companies/get-company-profile-with-job-postings.use-case';
import { IReapplyCompanyVerificationUseCase } from 'src/domain/interfaces/use-cases/company/profile/verification/IReapplyCompanyVerificationUseCase';
import { ReapplyCompanyVerificationUseCase } from 'src/application/use-cases/company/profile/verification/reapply-company-verification.use-case';
import { IGetCompanyContactUseCase } from 'src/domain/interfaces/use-cases/company/profile/contacts/IGetCompanyContactUseCase';
import { GetCompanyContactUseCase } from 'src/application/use-cases/company/profile/contacts/get-company-contact.use-case';
import { IUpsertCompanyContactUseCase } from 'src/domain/interfaces/use-cases/company/profile/contacts/IUpsertCompanyContactUseCase';
import { UpsertCompanyContactUseCase } from 'src/application/use-cases/company/profile/contacts/upsert-company-contact.use-case';
import { IGetCompanyProfileByUserIdUseCase } from 'src/domain/interfaces/use-cases/company/profile/info/IGetCompanyProfileByUserIdUseCase';
import { GetCompanyProfileByUserIdUseCase } from 'src/application/use-cases/company/profile/info/get-company-profile-by-user-id.use-case';
import { ICreateCompanyTechStackUseCase } from 'src/domain/interfaces/use-cases/company/profile/stack/ICreateCompanyTechStackUseCase';
import { CreateCompanyTechStackUseCase } from 'src/application/use-cases/company/profile/stack/create-company-tech-stack.use-case';
import { IUpdateCompanyTechStackUseCase } from 'src/domain/interfaces/use-cases/company/profile/stack/IUpdateCompanyTechStackUseCase';
import { UpdateCompanyTechStackUseCase } from 'src/application/use-cases/company/profile/stack/update-company-tech-stack.use-case';
import { IDeleteCompanyTechStackUseCase } from 'src/domain/interfaces/use-cases/company/profile/stack/IDeleteCompanyTechStackUseCase';
import { DeleteCompanyTechStackUseCase } from 'src/application/use-cases/company/profile/stack/delete-company-tech-stack.use-case';
import { IGetCompanyTechStackUseCase } from 'src/domain/interfaces/use-cases/company/profile/stack/IGetCompanyTechStackUseCase';
import { GetCompanyTechStackUseCase } from 'src/application/use-cases/company/profile/stack/get-company-tech-stack.use-case';
import { ICreateCompanyOfficeLocationUseCase } from 'src/domain/interfaces/use-cases/company/profile/location/ICreateCompanyOfficeLocationUseCase';
import { CreateCompanyOfficeLocationUseCase } from 'src/application/use-cases/company/profile/location/create-company-office-location.use-case';
import { IUpdateCompanyOfficeLocationUseCase } from 'src/domain/interfaces/use-cases/company/profile/location/IUpdateCompanyOfficeLocationUseCase';
import { UpdateCompanyOfficeLocationUseCase } from 'src/application/use-cases/company/profile/location/update-company-office-location.use-case';
import { IDeleteCompanyOfficeLocationUseCase } from 'src/domain/interfaces/use-cases/company/profile/location/IDeleteCompanyOfficeLocationUseCase';
import { DeleteCompanyOfficeLocationUseCase } from 'src/application/use-cases/company/profile/location/delete-company-office-location.use-case';
import { IGetCompanyOfficeLocationUseCase } from 'src/domain/interfaces/use-cases/company/profile/location/IGetCompanyOfficeLocationUseCase';
import { GetCompanyOfficeLocationUseCase } from 'src/application/use-cases/company/profile/location/get-company-office-location.use-case';
import { ICreateCompanyBenefitUseCase } from 'src/domain/interfaces/use-cases/company/profile/benefits/ICreateCompanyBenefitUseCase';
import { CreateCompanyBenefitUseCase } from 'src/application/use-cases/company/profile/benefits/create-company-benefit.use-case';
import { IUpdateCompanyBenefitUseCase } from 'src/domain/interfaces/use-cases/company/profile/benefits/IUpdateCompanyBenefitUseCase';
import { UpdateCompanyBenefitUseCase } from 'src/application/use-cases/company/profile/benefits/update-company-benefit.use-case';
import { IDeleteCompanyBenefitUseCase } from 'src/domain/interfaces/use-cases/company/profile/benefits/IDeleteCompanyBenefitUseCase';
import { DeleteCompanyBenefitUseCase } from 'src/application/use-cases/company/profile/benefits/delete-company-benefit.use-case';
import { IGetCompanyBenefitUseCase } from 'src/domain/interfaces/use-cases/company/profile/benefits/IGetCompanyBenefitUseCase';
import { GetCompanyBenefitUseCase } from 'src/application/use-cases/company/profile/benefits/get-company-benefit.use-case';
import { ICreateCompanyWorkplacePictureUseCase } from 'src/domain/interfaces/use-cases/company/media/ICreateCompanyWorkplacePictureUseCase';
import { CreateCompanyWorkplacePictureUseCase } from 'src/application/use-cases/company/media/create-company-workplace-picture.use-case';
import { IUpdateCompanyWorkplacePictureUseCase } from 'src/domain/interfaces/use-cases/company/media/IUpdateCompanyWorkplacePictureUseCase';
import { UpdateCompanyWorkplacePictureUseCase } from 'src/application/use-cases/company/media/update-company-workplace-picture.use-case';
import { IDeleteCompanyWorkplacePictureUseCase } from 'src/domain/interfaces/use-cases/company/media/IDeleteCompanyWorkplacePictureUseCase';
import { DeleteCompanyWorkplacePictureUseCase } from 'src/application/use-cases/company/media/delete-company-workplace-picture.use-case';
import { IGetCompanyWorkplacePictureUseCase } from 'src/domain/interfaces/use-cases/company/media/IGetCompanyWorkplacePictureUseCase';
import { GetCompanyWorkplacePictureUseCase } from 'src/application/use-cases/company/media/get-company-workplace-picture.use-case';
import { IUploadLogoUseCase } from 'src/domain/interfaces/use-cases/company/media/IUploadLogoUseCase';
import { UploadLogoUseCase } from 'src/application/use-cases/company/media/upload-logo.use-case';
import { IUploadBusinessLicenseUseCase } from 'src/domain/interfaces/use-cases/company/media/IUploadBusinessLicenseUseCase';
import { UploadBusinessLicenseUseCase } from 'src/application/use-cases/company/media/upload-business-license.use-case';
import { IUploadWorkplacePictureUseCase } from 'src/domain/interfaces/use-cases/company/media/IUploadWorkplacePictureUseCase';
import { UploadWorkplacePictureUseCase } from 'src/application/use-cases/company/media/upload-workplace-picture.use-case';
import { IDeleteImageUseCase } from 'src/domain/interfaces/use-cases/company/media/IDeleteImageUseCase';
import { DeleteImageUseCase } from 'src/application/use-cases/company/media/delete-image.use-case';

import { ICreateJobPostingUseCase } from 'src/domain/interfaces/use-cases/job/ICreateJobPostingUseCase';
import { CreateJobPostingUseCase } from 'src/application/use-cases/job/create-job-posting.use-case';
import { IGetCompanyJobPostingUseCase } from 'src/domain/interfaces/use-cases/job/IGetCompanyJobPostingUseCase';
import { GetCompanyJobPostingUseCase } from 'src/application/use-cases/job/get-company-job-posting.use-case';
import { IGetCompanyJobPostingsUseCase } from 'src/domain/interfaces/use-cases/job/IGetCompanyJobPostingsUseCase';
import { GetCompanyJobPostingsUseCase } from 'src/application/use-cases/job/get-company-job-postings.use-case';
import { IUpdateJobPostingUseCase } from 'src/domain/interfaces/use-cases/job/IUpdateJobPostingUseCase';
import { UpdateJobPostingUseCase } from 'src/application/use-cases/job/update-job-posting.use-case';
import { IDeleteJobPostingUseCase } from 'src/domain/interfaces/use-cases/job/IDeleteJobPostingUseCase';
import { DeleteJobPostingUseCase } from 'src/application/use-cases/job/delete-job-posting.use-case';
import { IUpdateJobStatusUseCase } from 'src/domain/interfaces/use-cases/job/IUpdateJobStatusUseCase';
import { UpdateJobStatusUseCase } from 'src/application/use-cases/job/update-job-status.use-case';
import { IGetApplicationsByJobUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IGetApplicationsByJobUseCase';
import { GetApplicationsByJobUseCase } from 'src/application/use-cases/company/hiring/get-applications-by-job.use-case';
import { IGetApplicationsByCompanyUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IGetApplicationsByCompanyUseCase';
import { GetApplicationsByCompanyUseCase } from 'src/application/use-cases/company/hiring/get-applications-by-company.use-case';
import { IGetApplicationDetailsUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IGetApplicationDetailsUseCase';
import { GetApplicationDetailsUseCase } from 'src/application/use-cases/company/hiring/get-application-details.use-case';
import { IUpdateApplicationStageUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IUpdateApplicationStageUseCase';
import { UpdateApplicationStageUseCase } from 'src/application/use-cases/company/hiring/update-application-stage.use-case';
import { IUpdateApplicationScoreUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IUpdateApplicationScoreUseCase';
import { UpdateApplicationScoreUseCase } from 'src/application/use-cases/company/hiring/update-application-score.use-case';
import { IBulkUpdateApplicationsUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IBulkUpdateApplicationsUseCase';
import { BulkUpdateApplicationsUseCase } from 'src/application/use-cases/company/hiring/bulk-update-applications.use-case';
import { IGetCandidatesUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IGetCandidatesUseCase';
import { GetCandidatesUseCase } from 'src/application/use-cases/company/hiring/get-candidates.use-case';
import { IGetCandidateDetailsUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IGetCandidateDetailsUseCase';
import { GetCandidateDetailsUseCase } from 'src/application/use-cases/company/hiring/get-candidate-details.use-case';
import { IMarkCandidateHiredUseCase } from 'src/domain/interfaces/use-cases/company/hiring/IMarkCandidateHiredUseCase';
import { MarkCandidateHiredUseCase } from 'src/application/use-cases/company/hiring/mark-candidate-hired.use-case';
import { ICloseJobManuallyUseCase } from 'src/domain/interfaces/use-cases/job/ICloseJobManuallyUseCase';
import { CloseJobManuallyUseCase } from 'src/application/use-cases/job/close-job-manually.use-case';
import { IReopenJobUseCase } from 'src/domain/interfaces/use-cases/job/IReopenJobUseCase';
import { ReopenJobUseCase } from 'src/application/use-cases/job/reopen-job.use-case';
import { IToggleFeaturedJobUseCase } from 'src/domain/interfaces/use-cases/job/IToggleFeaturedJobUseCase';
import { ToggleFeaturedJobUseCase } from 'src/application/use-cases/job/toggle-featured-job.use-case';
import { IGetCompanyDashboardStatsUseCase } from 'src/domain/interfaces/use-cases/company/dashboard/IGetCompanyDashboardStatsUseCase';
import { GetCompanyDashboardStatsUseCase } from 'src/application/use-cases/company/dashboard/get-company-dashboard-stats.use-case';

import { IGetActiveSubscriptionUseCase } from 'src/domain/interfaces/use-cases/subscription/IGetActiveSubscriptionUseCase';
import { GetActiveSubscriptionUseCase } from 'src/application/use-cases/subscription/get-active-subscription.use-case';
import { IGetPaymentHistoryUseCase } from 'src/domain/interfaces/use-cases/payment/history/IGetPaymentHistoryUseCase';
import { GetPaymentHistoryUseCase } from 'src/application/use-cases/payment/history/get-payment-history.use-case';
import { ICreateCheckoutSessionUseCase } from 'src/domain/interfaces/use-cases/subscription/ICreateCheckoutSessionUseCase';
import { CreateCheckoutSessionUseCase } from 'src/application/use-cases/subscription/create-checkout-session.use-case';
import { IRevertToDefaultPlanUseCase } from 'src/domain/interfaces/use-cases/subscription/IRevertToDefaultPlanUseCase';
import { RevertToDefaultPlanUseCase } from 'src/application/use-cases/subscription/revert-to-default-plan.use-case';
import { IHandleStripeWebhookUseCase } from 'src/domain/interfaces/use-cases/payment/stripe/IHandleStripeWebhookUseCase';
import { HandleStripeWebhookUseCase } from 'src/application/use-cases/payment/stripe/handle-stripe-webhook.use-case';
import { ICancelSubscriptionUseCase } from 'src/domain/interfaces/use-cases/subscription/ICancelSubscriptionUseCase';
import { CancelSubscriptionUseCase } from 'src/application/use-cases/subscription/cancel-subscription.use-case';
import { IResumeSubscriptionUseCase } from 'src/domain/interfaces/use-cases/subscription/IResumeSubscriptionUseCase';
import { ResumeSubscriptionUseCase } from 'src/application/use-cases/subscription/resume-subscription.use-case';
import { IChangeSubscriptionPlanUseCase } from 'src/domain/interfaces/use-cases/subscription/IChangeSubscriptionPlanUseCase';
import { ChangeSubscriptionPlanUseCase } from 'src/application/use-cases/subscription/change-subscription-plan.use-case';
import { IPreviewPlanChangeUseCase } from 'src/domain/interfaces/use-cases/subscription/IPreviewPlanChangeUseCase';
import { PreviewPlanChangeUseCase } from 'src/application/use-cases/subscription/preview-plan-change.use-case';
import { IGetBillingPortalUseCase } from 'src/domain/interfaces/use-cases/subscription/IGetBillingPortalUseCase';
import { GetBillingPortalUseCase } from 'src/application/use-cases/subscription/get-billing-portal.use-case';

import { CompanyProfileController } from 'src/presentation/controllers/company/profile/company-profile.controller';
import { CompanyContactController } from 'src/presentation/controllers/company/profile/company-contact.controller';
import { CompanyTechStackController } from 'src/presentation/controllers/company/profile/company-tech-stack.controller';
import { CompanyOfficeLocationController } from 'src/presentation/controllers/company/profile/company-office-location.controller';
import { CompanyBenefitController } from 'src/presentation/controllers/company/profile/company-benefit.controller';
import { CompanyWorkplacePictureController } from 'src/presentation/controllers/company/media/company-workplace-picture.controller';
import { CompanyUploadController } from 'src/presentation/controllers/company/media/company-upload.controller';
import { CompanyJobPostingController } from 'src/presentation/controllers/company/jobs/company-job-posting.controller';
import { CompanyJobApplicationController } from 'src/presentation/controllers/company/hiring/job-application.controller';
import { CompanySubscriptionPlanController } from 'src/presentation/controllers/company/subscription/company-subscription-plan.controller';
import { CompanySubscriptionController } from 'src/presentation/controllers/company/subscription/company-subscription.controller';
import { CompanyCandidatesController } from 'src/presentation/controllers/company/hiring/company-candidates.controller';
import { CompanyDashboardController } from 'src/presentation/controllers/company/dashboard/company-dashboard.controller';
import { StripeWebhookController } from 'src/presentation/controllers/payment/stripe-webhook.controller';
import { SubscriptionMiddleware } from 'src/presentation/middleware/subscription.middleware';
import { IStripeService } from 'src/domain/interfaces/services/IStripeService';
import { StripeService } from 'src/infrastructure/external-services/stripe/stripe.service';

export function registerCompanyDi(container: Container): void {
  container.bind<IStripeService>(TYPES.StripeService).to(StripeService).inSingletonScope();

  container.bind<ICreateCompanyProfileUseCase>(TYPES.CreateCompanyProfileUseCase).to(CreateCompanyProfileUseCase);
  container.bind<ICreateCompanyProfileFromDtoUseCase>(TYPES.CreateCompanyProfileFromDtoUseCase).to(CreateCompanyProfileFromDtoUseCase);
  container.bind<IUpdateCompanyProfileUseCase>(TYPES.UpdateCompanyProfileUseCase).to(UpdateCompanyProfileUseCase);
  container.bind<IGetCompanyProfileWithJobPostingsUseCase>(TYPES.GetCompanyProfileWithJobPostingsUseCase).to(GetCompanyProfileWithJobPostingsUseCase);
  container.bind<IReapplyCompanyVerificationUseCase>(TYPES.ReapplyCompanyVerificationUseCase).to(ReapplyCompanyVerificationUseCase);
  container.bind<IGetCompanyContactUseCase>(TYPES.GetCompanyContactUseCase).to(GetCompanyContactUseCase);
  container.bind<IUpsertCompanyContactUseCase>(TYPES.UpsertCompanyContactUseCase).to(UpsertCompanyContactUseCase);
  container.bind<IGetCompanyProfileByUserIdUseCase>(TYPES.GetCompanyProfileByUserIdUseCase).to(GetCompanyProfileByUserIdUseCase);
  container.bind<ICreateCompanyTechStackUseCase>(TYPES.CreateCompanyTechStackUseCase).to(CreateCompanyTechStackUseCase);
  container.bind<IUpdateCompanyTechStackUseCase>(TYPES.UpdateCompanyTechStackUseCase).to(UpdateCompanyTechStackUseCase);
  container.bind<IDeleteCompanyTechStackUseCase>(TYPES.DeleteCompanyTechStackUseCase).to(DeleteCompanyTechStackUseCase);
  container.bind<IGetCompanyTechStackUseCase>(TYPES.GetCompanyTechStackUseCase).to(GetCompanyTechStackUseCase);
  container.bind<ICreateCompanyOfficeLocationUseCase>(TYPES.CreateCompanyOfficeLocationUseCase).to(CreateCompanyOfficeLocationUseCase);
  container.bind<IUpdateCompanyOfficeLocationUseCase>(TYPES.UpdateCompanyOfficeLocationUseCase).to(UpdateCompanyOfficeLocationUseCase);
  container.bind<IDeleteCompanyOfficeLocationUseCase>(TYPES.DeleteCompanyOfficeLocationUseCase).to(DeleteCompanyOfficeLocationUseCase);
  container.bind<IGetCompanyOfficeLocationUseCase>(TYPES.GetCompanyOfficeLocationUseCase).to(GetCompanyOfficeLocationUseCase);
  container.bind<ICreateCompanyBenefitUseCase>(TYPES.CreateCompanyBenefitUseCase).to(CreateCompanyBenefitUseCase);
  container.bind<IUpdateCompanyBenefitUseCase>(TYPES.UpdateCompanyBenefitUseCase).to(UpdateCompanyBenefitUseCase);
  container.bind<IDeleteCompanyBenefitUseCase>(TYPES.DeleteCompanyBenefitUseCase).to(DeleteCompanyBenefitUseCase);
  container.bind<IGetCompanyBenefitUseCase>(TYPES.GetCompanyBenefitUseCase).to(GetCompanyBenefitUseCase);
  container.bind<ICreateCompanyWorkplacePictureUseCase>(TYPES.CreateCompanyWorkplacePictureUseCase).to(CreateCompanyWorkplacePictureUseCase);
  container.bind<IUpdateCompanyWorkplacePictureUseCase>(TYPES.UpdateCompanyWorkplacePictureUseCase).to(UpdateCompanyWorkplacePictureUseCase);
  container.bind<IDeleteCompanyWorkplacePictureUseCase>(TYPES.DeleteCompanyWorkplacePictureUseCase).to(DeleteCompanyWorkplacePictureUseCase);
  container.bind<IGetCompanyWorkplacePictureUseCase>(TYPES.GetCompanyWorkplacePictureUseCase).to(GetCompanyWorkplacePictureUseCase);
  container.bind<IUploadLogoUseCase>(TYPES.UploadLogoUseCase).to(UploadLogoUseCase);
  container.bind<IUploadBusinessLicenseUseCase>(TYPES.UploadBusinessLicenseUseCase).to(UploadBusinessLicenseUseCase);
  container.bind<IUploadWorkplacePictureUseCase>(TYPES.UploadWorkplacePictureUseCase).to(UploadWorkplacePictureUseCase);
  container.bind<IDeleteImageUseCase>(TYPES.DeleteImageUseCase).to(DeleteImageUseCase);

  container.bind<ICreateJobPostingUseCase>(TYPES.CreateJobPostingUseCase).to(CreateJobPostingUseCase);
  container.bind<IGetCompanyJobPostingUseCase>(TYPES.GetCompanyJobPostingUseCase).to(GetCompanyJobPostingUseCase);
  container.bind<IGetCompanyJobPostingsUseCase>(TYPES.GetCompanyJobPostingsUseCase).to(GetCompanyJobPostingsUseCase);
  container.bind<IUpdateJobPostingUseCase>(TYPES.UpdateJobPostingUseCase).to(UpdateJobPostingUseCase);
  container.bind<IDeleteJobPostingUseCase>(TYPES.DeleteJobPostingUseCase).to(DeleteJobPostingUseCase);
  container.bind<IUpdateJobStatusUseCase>(TYPES.UpdateJobStatusUseCase).to(UpdateJobStatusUseCase);
  container.bind<IGetApplicationsByJobUseCase>(TYPES.GetApplicationsByJobUseCase).to(GetApplicationsByJobUseCase);
  container.bind<IGetApplicationsByCompanyUseCase>(TYPES.GetApplicationsByCompanyUseCase).to(GetApplicationsByCompanyUseCase);
  container.bind<IGetApplicationDetailsUseCase>(TYPES.GetCompanyApplicationDetailsUseCase).to(GetApplicationDetailsUseCase);
  container.bind<IUpdateApplicationStageUseCase>(TYPES.CompanyUpdateApplicationStageUseCase).to(UpdateApplicationStageUseCase);
  container.bind<IUpdateApplicationScoreUseCase>(TYPES.UpdateApplicationScoreUseCase).to(UpdateApplicationScoreUseCase);
  container.bind<IBulkUpdateApplicationsUseCase>(TYPES.BulkUpdateApplicationsUseCase).to(BulkUpdateApplicationsUseCase);
  container.bind<IGetCandidatesUseCase>(TYPES.GetCandidatesUseCase).to(GetCandidatesUseCase);
  container.bind<IGetCandidateDetailsUseCase>(TYPES.GetCandidateDetailsUseCase).to(GetCandidateDetailsUseCase);
  container.bind<IMarkCandidateHiredUseCase>(TYPES.MarkCandidateHiredUseCase).to(MarkCandidateHiredUseCase);
  container.bind<ICloseJobManuallyUseCase>(TYPES.CloseJobManuallyUseCase).to(CloseJobManuallyUseCase);
  container.bind<IReopenJobUseCase>(TYPES.ReopenJobUseCase).to(ReopenJobUseCase);
  container.bind<IToggleFeaturedJobUseCase>(TYPES.ToggleFeaturedJobUseCase).to(ToggleFeaturedJobUseCase);
  container.bind<IGetCompanyDashboardStatsUseCase>(TYPES.GetCompanyDashboardStatsUseCase).to(GetCompanyDashboardStatsUseCase);

  container.bind<IGetActiveSubscriptionUseCase>(TYPES.GetActiveSubscriptionUseCase).to(GetActiveSubscriptionUseCase);
  container.bind<IGetPaymentHistoryUseCase>(TYPES.GetPaymentHistoryUseCase).to(GetPaymentHistoryUseCase);
  container.bind<ICreateCheckoutSessionUseCase>(TYPES.CreateCheckoutSessionUseCase).to(CreateCheckoutSessionUseCase);
  container.bind<IRevertToDefaultPlanUseCase>(TYPES.RevertToDefaultPlanUseCase).to(RevertToDefaultPlanUseCase);
  container.bind<IHandleStripeWebhookUseCase>(TYPES.HandleStripeWebhookUseCase).to(HandleStripeWebhookUseCase);
  container.bind<ICancelSubscriptionUseCase>(TYPES.CancelSubscriptionUseCase).to(CancelSubscriptionUseCase);
  container.bind<IResumeSubscriptionUseCase>(TYPES.ResumeSubscriptionUseCase).to(ResumeSubscriptionUseCase);
  container.bind<IChangeSubscriptionPlanUseCase>(TYPES.ChangeSubscriptionPlanUseCase).to(ChangeSubscriptionPlanUseCase);
  container.bind<IPreviewPlanChangeUseCase>(TYPES.PreviewPlanChangeUseCase).to(PreviewPlanChangeUseCase);
  container.bind<IGetBillingPortalUseCase>(TYPES.GetBillingPortalUseCase).to(GetBillingPortalUseCase);

  container.bind<CompanyProfileController>(TYPES.CompanyProfileController).to(CompanyProfileController);
  container.bind<CompanyContactController>(TYPES.CompanyContactController).to(CompanyContactController);
  container.bind<CompanyTechStackController>(TYPES.CompanyTechStackController).to(CompanyTechStackController);
  container.bind<CompanyOfficeLocationController>(TYPES.CompanyOfficeLocationController).to(CompanyOfficeLocationController);
  container.bind<CompanyBenefitController>(TYPES.CompanyBenefitController).to(CompanyBenefitController);
  container.bind<CompanyWorkplacePictureController>(TYPES.CompanyWorkplacePictureController).to(CompanyWorkplacePictureController);
  container.bind<CompanyUploadController>(TYPES.CompanyUploadController).to(CompanyUploadController);
  container.bind<CompanyJobPostingController>(TYPES.CompanyJobPostingController).to(CompanyJobPostingController);
  container.bind<CompanyJobApplicationController>(TYPES.CompanyJobApplicationController).to(CompanyJobApplicationController);
  container.bind<CompanySubscriptionPlanController>(TYPES.CompanySubscriptionPlanController).to(CompanySubscriptionPlanController);
  container.bind<CompanySubscriptionController>(TYPES.CompanySubscriptionController).to(CompanySubscriptionController);
  container.bind<CompanyCandidatesController>(TYPES.CompanyCandidatesController).to(CompanyCandidatesController);
  container.bind<CompanyDashboardController>(TYPES.CompanyDashboardController).to(CompanyDashboardController);
  container.bind<StripeWebhookController>(TYPES.StripeWebhookController).to(StripeWebhookController);
  container.bind<SubscriptionMiddleware>(TYPES.SubscriptionMiddleware).to(SubscriptionMiddleware);
}
