export const AdminRoutes = {
  USERS: '/api/admin/users',
  USERS_BLOCK: '/api/admin/users/block',
  USERS_ID: '/api/admin/users/:id',
  COMPANIES: '/api/admin/companies',
  COMPANIES_VERIFICATION: '/api/admin/companies/verification',
  COMPANIES_VERIFY: '/api/admin/companies/verify',
  JOBS: '/api/admin/jobs',
  JOBS_STATS: '/api/admin/jobs/stats',
  JOBS_ID: '/api/admin/jobs/:id',
  JOBS_ID_STATUS: '/api/admin/jobs/:id/status',
  JOB_CATEGORIES: '/api/admin/job-categories',
  JOB_CATEGORIES_ID: '/api/admin/job-categories/:id',
  SKILLS: '/api/admin/skills',
  SKILLS_ID: '/api/admin/skills/:id',
  JOB_ROLES: '/api/admin/job-roles',
  JOB_ROLES_ID: '/api/admin/job-roles/:id',
  SUBSCRIPTION_PLANS: '/api/admin/subscription-plans',
  SUBSCRIPTION_PLANS_ID: '/api/admin/subscription-plans/:id',
  SUBSCRIPTION_PLANS_MIGRATE: '/api/admin/subscription-plans/:id/migrate-subscribers',
  PAYMENT_ORDERS: '/api/admin/payment-orders',
  DASHBOARD_STATS: '/api/admin/dashboard/stats',
} as const;

export const AuthRoutes = {
  REGISTER: '/api/auth/register',
  LOGIN: '/api/auth/login',
  ADMIN_LOGIN: '/api/auth/admin-login',
  GOOGLE_LOGIN: '/api/auth/login/google',
  REFRESH: '/api/auth/refresh',
  CHECK_AUTH: '/api/auth/check-auth',
  FORGOT_PASSWORD: '/api/auth/forgot-password',
  RESET_PASSWORD: '/api/auth/reset-password',
  LOGOUT: '/api/auth/logout',
  OTP_REQUEST: '/api/auth/otp-request',
  OTP_VERIFY: '/api/auth/otp-verify',
} as const;

export const ChatRoutes = {
  CONVERSATIONS: '/api/chat/conversations',
  CONVERSATIONS_MESSAGES: '/api/chat/conversations/:conversationId/messages',
  CONVERSATIONS_READ: '/api/chat/conversations/:conversationId/read',
  MESSAGES: '/api/chat/messages',
  MESSAGES_DELETE: '/api/chat/messages/:messageId',
} as const;

export const CompanyRoutes = {
  PROFILE: '/api/company/profile',
  PROFILE_BY_ID: '/api/company/profile/:profileId',
  CANDIDATES: '/api/company/candidates',
  REAPPLY_VERIFICATION: '/api/company/reapply-verification',
  UPLOAD_LOGO: '/api/company/upload/logo',
  UPLOAD_BUSINESS_LICENSE: '/api/company/upload/business-license',
  DELETE_UPLOAD: '/api/company/upload/delete',
  SUBSCRIPTION_PLANS: '/api/company/subscription-plans',
  DASHBOARD: '/api/company/dashboard',
  DASHBOARD_STATS: '/api/company/dashboard/stats',
  CONTACT: '/api/company/contact',
  TECH_STACKS: '/api/company/tech-stacks',
  TECH_STACKS_ID: '/api/company/tech-stacks/:id',
  OFFICE_LOCATIONS: '/api/company/office-locations',
  OFFICE_LOCATIONS_ID: '/api/company/office-locations/:id',
  BENEFITS: '/api/company/benefits',
  BENEFITS_ID: '/api/company/benefits/:id',
  WORKPLACE_PICTURES: '/api/company/workplace-pictures',
  WORKPLACE_PICTURES_ID: '/api/company/workplace-pictures/:id',
  WORKPLACE_PICTURES_UPLOAD: '/api/company/workplace-pictures/upload',
  SUBSCRIPTIONS_ACTIVE: '/api/company/subscriptions/active',
  SUBSCRIPTIONS_PAYMENT_HISTORY: '/api/company/subscriptions/payment-history',
  SUBSCRIPTIONS_CREATE_CHECKOUT: '/api/company/subscriptions/create-checkout-session',
  SUBSCRIPTIONS_CANCEL: '/api/company/subscriptions/cancel',
  SUBSCRIPTIONS_RESUME: '/api/company/subscriptions/resume',
  SUBSCRIPTIONS_PURCHASE: '/api/company/subscriptions/purchase',
  SUBSCRIPTIONS_CHANGE_PLAN: '/api/company/subscriptions/change-plan',
  SUBSCRIPTIONS_BILLING_PORTAL: '/api/company/subscriptions/billing-portal',
  JOBS: '/api/company/jobs',
  JOBS_ID: '/api/company/jobs/:id',
  JOBS_ID_STATUS: '/api/company/jobs/:id/status',
  JOBS_ID_CLOSE: '/api/company/jobs/:id/close',
  JOBS_ID_REOPEN: '/api/company/jobs/:id/reopen',
  APPLICATIONS: '/api/company/applications',
  APPLICATIONS_BULK_UPDATE: '/api/company/applications/bulk-update',
  APPLICATIONS_ID: '/api/company/applications/:id',
  APPLICATIONS_ID_STAGE: '/api/company/applications/:id/stage',
  APPLICATIONS_ID_SCORE: '/api/company/applications/:id/score',
  APPLICATIONS_ID_MARK_HIRED: '/api/company/applications/:id/mark-hired',
  APPLICATIONS_ID_INTERVIEWS: '/api/company/applications/:id/interviews',
  APPLICATIONS_ID_INTERVIEWS_INTERVIEW_ID: '/api/company/applications/:id/interviews/:interviewId',
  APPLICATIONS_ID_INTERVIEWS_INTERVIEW_DELETE: '/api/company/applications/:id/interviews/:interviewId',
  APPLICATIONS_ID_INTERVIEWS_FEEDBACK: '/api/company/applications/:id/interviews/:interviewId/feedback',
  JOBS_ID_ATS_PIPELINE: '/api/company/jobs/:jobId/ats-pipeline',
  JOBS_ID_APPLICATIONS: '/api/company/jobs/:jobId/applications',
  APPLICATIONS_ID_MOVE_STAGE: '/api/company/applications/:id/move-stage',
  APPLICATIONS_ID_UPDATE_SUB_STAGE: '/api/company/applications/:id/update-sub-stage',
} as const;

export const NotificationRoutes = {
  GET_NOTIFICATIONS: '/api/notifications/',
  UNREAD_COUNT: '/api/notifications/unread-count',
  MARK_READ: '/api/notifications/:id/read',
  READ_ALL: '/api/notifications/read-all',
} as const;

export const PublicRoutes = {
  JOBS: '/api/public/jobs',
  JOBS_ID: '/api/public/jobs/:id',
  SKILLS: '/api/public/skills',
  JOB_CATEGORIES: '/api/public/job-categories',
  JOB_ROLES: '/api/public/job-roles',
  COMPANIES: '/api/public/companies',
} as const;


export const SeekerRoutes = {
  PROFILE: '/api/seeker/profile',
  PROFILE_EXPERIENCES: '/api/seeker/profile/experiences',
  PROFILE_EXPERIENCES_ID: '/api/seeker/profile/experiences/:experienceId',
  PROFILE_EDUCATION: '/api/seeker/profile/education',
  PROFILE_EDUCATION_ID: '/api/seeker/profile/education/:educationId',
  PROFILE_SKILLS: '/api/seeker/profile/skills',
  PROFILE_LANGUAGES: '/api/seeker/profile/languages',
  PROFILE_RESUME: '/api/seeker/profile/resume',
  PROFILE_AVATAR: '/api/seeker/profile/avatar',
  PROFILE_BANNER: '/api/seeker/profile/banner',
  APPLICATIONS: '/api/seeker/applications',
  APPLICATIONS_ANALYZE_RESUME: '/api/seeker/applications/analyze-resume',
  APPLICATIONS_ID: '/api/seeker/applications/:id',
  APPLICATIONS_ID_INTERVIEWS: '/api/seeker/applications/:id/interviews',
  APPLICATIONS_ID_TASKS: '/api/seeker/applications/:id/tasks',
} as const;
