
export enum ATSStage {
  APPLIED = 'APPLIED',
  IN_REVIEW = 'IN_REVIEW',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW = 'INTERVIEW',
  TECHNICAL_TASK = 'TECHNICAL_TASK',
  COMPENSATION = 'COMPENSATION',
  OFFER = 'OFFER',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED',
}


export enum InReviewSubStage {
  PROFILE_REVIEW = 'PROFILE_REVIEW',
  PENDING_DECISION = 'PENDING_DECISION',
}


export enum ShortlistedSubStage {
  READY_FOR_INTERVIEW = 'READY_FOR_INTERVIEW',
  CONTACTED = 'CONTACTED',
  AWAITING_RESPONSE = 'AWAITING_RESPONSE',
}


export enum InterviewSubStage {
  NOT_SCHEDULED = 'NOT_SCHEDULED',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  EVALUATION_PENDING = 'EVALUATION_PENDING',
}


export enum TechnicalTaskSubStage {
  NOT_ASSIGNED = 'NOT_ASSIGNED',
  ASSIGNED = 'ASSIGNED',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  COMPLETED = 'COMPLETED',
}


export enum CompensationSubStage {
  NOT_INITIATED = 'NOT_INITIATED',
  INITIATED = 'INITIATED',
  NEGOTIATION_ONGOING = 'NEGOTIATION_ONGOING',
  APPROVED = 'APPROVED',
}


export enum OfferSubStage {
  NOT_SENT = 'NOT_SENT',
  OFFER_SENT = 'OFFER_SENT',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
}

export type ATSSubStage =
  | InReviewSubStage
  | ShortlistedSubStage
  | InterviewSubStage
  | TechnicalTaskSubStage
  | CompensationSubStage
  | OfferSubStage;




