// Main ATS Stages (Kanban Columns)
export enum ATSStage {
  IN_REVIEW = 'IN_REVIEW',
  SHORTLISTED = 'SHORTLISTED',
  INTERVIEW = 'INTERVIEW',
  TECHNICAL_TASK = 'TECHNICAL_TASK',
  COMPENSATION = 'COMPENSATION',
  OFFER = 'OFFER',
}

// Sub-Stages for IN_REVIEW
export enum InReviewSubStage {
  PROFILE_REVIEW = 'PROFILE_REVIEW', // default
  PENDING_DECISION = 'PENDING_DECISION',
}

// Sub-Stages for SHORTLISTED
export enum ShortlistedSubStage {
  READY_FOR_INTERVIEW = 'READY_FOR_INTERVIEW', // default
  CONTACTED = 'CONTACTED', // optional
  AWAITING_RESPONSE = 'AWAITING_RESPONSE', // optional
}

// Sub-Stages for INTERVIEW
export enum InterviewSubStage {
  NOT_SCHEDULED = 'NOT_SCHEDULED',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  EVALUATION_PENDING = 'EVALUATION_PENDING',
}

// Sub-Stages for TECHNICAL_TASK
export enum TechnicalTaskSubStage {
  NOT_ASSIGNED = 'NOT_ASSIGNED',
  ASSIGNED = 'ASSIGNED',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  COMPLETED = 'COMPLETED',
}

// Sub-Stages for COMPENSATION
export enum CompensationSubStage {
  NOT_INITIATED = 'NOT_INITIATED',
  INITIATED = 'INITIATED',
  NEGOTIATION_ONGOING = 'NEGOTIATION_ONGOING',
  APPROVED = 'APPROVED',
}

// Sub-Stages for OFFER
export enum OfferSubStage {
  NOT_SENT = 'NOT_SENT',
  OFFER_SENT = 'OFFER_SENT',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
}

export type ATSSubStage = 
  | InReviewSubStage
  | ShortlistedSubStage
  | InterviewSubStage
  | TechnicalTaskSubStage
  | CompensationSubStage
  | OfferSubStage;

export enum ActivityType {
  STAGE_CHANGE = 'STAGE_CHANGE',
  SUBSTAGE_CHANGE = 'SUBSTAGE_CHANGE',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  INTERVIEW_CANCELLED = 'INTERVIEW_CANCELLED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_SUBMITTED = 'TASK_SUBMITTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  COMPENSATION_INITIATED = 'COMPENSATION_INITIATED',
  COMPENSATION_UPDATED = 'COMPENSATION_UPDATED',
  COMPENSATION_APPROVED = 'COMPENSATION_APPROVED',
  COMPENSATION_MEETING_SCHEDULED = 'COMPENSATION_MEETING_SCHEDULED',
  OFFER_SENT = 'OFFER_SENT',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  NOTE_ADDED = 'NOTE_ADDED'
}


