export enum AdminRoutes {
  USERS = '/users',
  USERS_BLOCK = '/users/block',
  USERS_ID = '/users/:id',
  COMPANIES = '/companies',
  COMPANIES_VERIFICATION = '/companies/verification',
  COMPANIES_VERIFY = '/companies/verify',
  JOBS = '/jobs',
  JOBS_STATS = '/jobs/stats',
  JOBS_ID = '/jobs/:id',
  JOBS_ID_STATUS = '/jobs/:id/status',
  JOB_CATEGORIES = '/job-categories',
  JOB_CATEGORIES_ID = '/job-categories/:id',
  SKILLS = '/skills',
  SKILLS_ID = '/skills/:id',
  JOB_ROLES = '/job-roles',
  JOB_ROLES_ID = '/job-roles/:id',
  SUBSCRIPTION_PLANS = '/subscription-plans',
  SUBSCRIPTION_PLANS_ID = '/subscription-plans/:id',
  SUBSCRIPTION_PLANS_MIGRATE = '/subscription-plans/:id/migrate-subscribers',
  PAYMENT_ORDERS = '/payment-orders',
}

export enum AuthRoutes {
  REGISTER = '/register',
  LOGIN = '/login',
  ADMIN_LOGIN = '/admin-login',
  GOOGLE_LOGIN = '/login/google',
  REFRESH = '/refresh',
  CHECK_AUTH = '/check-auth',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password',
  LOGOUT = '/logout',
  OTP_REQUEST = '/otp-request',
  OTP_VERIFY = '/otp-verify',
}

export enum ChatRoutes {
  CONVERSATIONS = '/conversations',
  CONVERSATIONS_MESSAGES = '/conversations/:conversationId/messages',
  CONVERSATIONS_READ = '/conversations/:conversationId/read',
  MESSAGES = '/messages',
  MESSAGES_DELETE = '/messages/:messageId',
}

export enum CompanyRoutes {
  PROFILE = '/profile',
  PROFILE_BY_ID = '/profile/:profileId',
  REAPPLY_VERIFICATION = '/reapply-verification',
  UPLOAD_LOGO = '/upload/logo',
  UPLOAD_BUSINESS_LICENSE = '/upload/business-license',
  DELETE_UPLOAD = '/upload/delete',
  SUBSCRIPTION_PLANS = '/subscription-plans',
  DASHBOARD = '/dashboard',
  CONTACT = '/contact',
  TECH_STACKS = '/tech-stacks',
  TECH_STACKS_ID = '/tech-stacks/:id',
  OFFICE_LOCATIONS = '/office-locations',
  OFFICE_LOCATIONS_ID = '/office-locations/:id',
  BENEFITS = '/benefits',
  BENEFITS_ID = '/benefits/:id',
  WORKPLACE_PICTURES = '/workplace-pictures',
  WORKPLACE_PICTURES_ID = '/workplace-pictures/:id',
  WORKPLACE_PICTURES_UPLOAD = '/workplace-pictures/upload',
  SUBSCRIPTIONS_ACTIVE = '/subscriptions/active',
  SUBSCRIPTIONS_PAYMENT_HISTORY = '/subscriptions/payment-history',
  SUBSCRIPTIONS_CREATE_CHECKOUT = '/subscriptions/create-checkout-session',
  SUBSCRIPTIONS_CANCEL = '/subscriptions/cancel',
  SUBSCRIPTIONS_RESUME = '/subscriptions/resume',
  SUBSCRIPTIONS_CHANGE_PLAN = '/subscriptions/change-plan',
  SUBSCRIPTIONS_BILLING_PORTAL = '/subscriptions/billing-portal',
  JOBS = '/jobs',
  JOBS_ID = '/jobs/:id',
  JOBS_ID_STATUS = '/jobs/:id/status',
  APPLICATIONS = '/applications',
  APPLICATIONS_BULK_UPDATE = '/applications/bulk-update',
  APPLICATIONS_ID = '/applications/:id',
  APPLICATIONS_ID_STAGE = '/applications/:id/stage',
  APPLICATIONS_ID_SCORE = '/applications/:id/score',
  APPLICATIONS_ID_INTERVIEWS = '/applications/:id/interviews',
  APPLICATIONS_ID_INTERVIEWS_INTERVIEW_ID = '/applications/:id/interviews/:interviewId',
  APPLICATIONS_ID_INTERVIEWS_INTERVIEW_DELETE = '/applications/:id/interviews/:interviewId',
  APPLICATIONS_ID_INTERVIEWS_FEEDBACK = '/applications/:id/interviews/:interviewId/feedback',
}

export enum NotificationRoutes {
  GET_NOTIFICATIONS = '/',
  UNREAD_COUNT = '/unread-count',
  MARK_READ = '/:id/read',
  READ_ALL = '/read-all',
}

export enum PublicRoutes {
  JOBS = '/jobs',
  JOBS_ID = '/jobs/:id',
  SKILLS = '/skills',
  JOB_CATEGORIES = '/job-categories',
  JOB_ROLES = '/job-roles',
}

export enum SeekerRoutes {
  PROFILE = '/profile',
  PROFILE_EXPERIENCES = '/profile/experiences',
  PROFILE_EXPERIENCES_ID = '/profile/experiences/:experienceId',
  PROFILE_EDUCATION = '/profile/education',
  PROFILE_EDUCATION_ID = '/profile/education/:educationId',
  PROFILE_SKILLS = '/profile/skills',
  PROFILE_LANGUAGES = '/profile/languages',
  PROFILE_RESUME = '/profile/resume',
  PROFILE_AVATAR = '/profile/avatar',
  PROFILE_BANNER = '/profile/banner',
  APPLICATIONS = '/applications',
  APPLICATIONS_ANALYZE_RESUME = '/applications/analyze-resume',
  APPLICATIONS_ID = '/applications/:id',
}
