function getEnv(key: string): string {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Required environment variable ${key} is not configured`);
  }
  return value;
}

export const env = {
  NODE_ENV: getEnv('NODE_ENV'),
  PORT: getEnv('PORT'),
  MONGO_URI: getEnv('MONGO_URI'),
  JWT_ACCESS_SECRET: getEnv('JWT_ACCESS_SECRET'),
  JWT_REFRESH_SECRET: getEnv('JWT_REFRESH_SECRET'),
  BCRYPT_SALT_ROUNDS: getEnv('BCRYPT_SALT_ROUNDS'),
  JWT_ACCESS_EXPIRES_IN: getEnv('JWT_ACCESS_EXPIRES_IN'),
  JWT_REFRESH_EXPIRES_IN: getEnv('JWT_REFRESH_EXPIRES_IN'),
  REDIS_URL: getEnv('REDIS_URL'),
  OTP_TTL_SECONDS: getEnv('OTP_TTL_SECONDS'),
  COOKIE_NAME_REFRESH: getEnv('COOKIE_NAME_REFRESH'),
  EMAIL_USER: getEnv('EMAIL_USER'),
  EMAIL_PASSWORD: getEnv('EMAIL_PASSWORD'),
  GOOGLE_CLIENT_ID: getEnv('GOOGLE_CLIENT_ID'),
  GOOGLE_CLIENT_SECRET: getEnv('GOOGLE_CLIENT_SECRET'),
  FRONTEND_URL: getEnv('FRONTEND_URL'),
  AWS_ACCESS_KEY_ID: getEnv('AWS_ACCESS_KEY_ID'),
  AWS_SECRET_ACCESS_KEY: getEnv('AWS_SECRET_ACCESS_KEY'),
  AWS_REGION: getEnv('AWS_REGION'),
  AWS_S3_BUCKET_NAME: getEnv('AWS_S3_BUCKET_NAME'),
  LOG_RETENTION_DAYS: getEnv('LOG_RETENTION_DAYS'),
  LOG_LEVEL: getEnv('LOG_LEVEL'),
  STRIPE_SECRET_KEY: getEnv('STRIPE_SECRET_KEY'),
  STRIPE_WEBHOOK_SECRET: getEnv('STRIPE_WEBHOOK_SECRET'),
};