import { ICompanySubscriptionRepository } from '../../../domain/interfaces/repositories/subscription/ICompanySubscriptionRepository';
import { ISubscriptionPlanRepository } from '../../../domain/interfaces/repositories/subscription-plan/ISubscriptionPlanRepository';
import { ICompanyProfileRepository } from '../../../domain/interfaces/repositories/company/ICompanyProfileRepository';
import { IPaymentOrderRepository } from '../../../domain/interfaces/repositories/payment/IPaymentOrderRepository';
import { CompanySubscription } from '../../../domain/entities/company-subscription.entity';
import { PaymentOrder } from '../../../domain/entities/payment-order.entity';
import { NotFoundError, ValidationError } from '../../../domain/errors/errors';

export class PurchaseSubscriptionUseCase {
  constructor(
    private _companySubscriptionRepository: ICompanySubscriptionRepository,
    private _subscriptionPlanRepository: ISubscriptionPlanRepository,
    private _companyProfileRepository: ICompanyProfileRepository,
    private _paymentOrderRepository: IPaymentOrderRepository,
  ) {}

  async execute(userId: string, planId: string): Promise<{ subscription: CompanySubscription; paymentOrder: PaymentOrder }> {
    // Get company profile
    const companyProfile = await this._companyProfileRepository.findOne({ userId });
    if (!companyProfile) {
      throw new NotFoundError('Company profile not found');
    }

    const companyId = companyProfile.id;

    // Check if plan exists and is active
    const plan = await this._subscriptionPlanRepository.findById(planId);
    if (!plan) {
      throw new NotFoundError('Subscription plan not found');
    }

    if (!plan.isActive) {
      throw new ValidationError('This subscription plan is not available');
    }

    // Check if company already has an active subscription
    const existingSubscription = await this._companySubscriptionRepository.findActiveByCompanyId(companyId);
    if (existingSubscription) {
      throw new ValidationError('You already have an active subscription. Please wait for it to expire or cancel it first.');
    }

    // Calculate dates
    const startDate = new Date();
    const expiryDate = new Date();
    expiryDate.setDate(expiryDate.getDate() + plan.duration);

    // Create payment order (dummy payment - auto success)
    const transactionId = `TXN-${Date.now()}-${Math.random().toString(36).substring(7)}`;
    const paymentOrder = await this._paymentOrderRepository.create(
      PaymentOrder.create({
        id: '', // Will be generated by MongoDB
        companyId,
        planId,
        amount: plan.price,
        currency: 'USD',
        status: 'completed', // Auto-complete for dummy payment
        paymentMethod: 'dummy',
        transactionId,
        metadata: {
          planName: plan.name,
          duration: plan.duration,
          userId,
        },
      }),
    );

    // Create subscription
    const subscription = await this._companySubscriptionRepository.create({
      companyId,
      planId,
      startDate,
      expiryDate,
      isActive: true,
      jobPostsUsed: 0,
      featuredJobsUsed: 0,
      applicantAccessUsed: 0,
    });

    return { subscription, paymentOrder };
  }
}
